### ISSUE TITLE
private types as a less-verbose substitute for the view pattern

### ISSUE THREAD

**Issue by russelldmatt** [ostera/reason-design-patterns#5]
More of a question than an issue, but wasn't sure where else to ask.

Don't private types achieve the semantics you want?  An exposed type which cannot be constructed but can be deconstructed.  Are you already aware of this and there's some additional value to the view pattern that I don't understand?

Here's some code which demonstrates what I mean: https://reasonml.github.io/en/try.html?rrjsx=true&reason=LYewJgrgNgpgBAVQM4wE4HUCWAXAFgNUxgHcAuOAbwCg45sBPAB3mwG4a6n4A3I4uALyUOtAHYBDYDHJJsqTKIDmAGhFxxi6XAXZVtAL7tasbHGDiA1loAUAPwlSZchSri2NWnQEpBAPjpGcCZwvCTkpgL+ocTs+oLCtAzMdPHUtGKSWrLySnrpHuQ6eYYcSTx8qWoOWc65agXaorocJcYwpuZW8XbVym4eXuF+lL3qmq1B7SF8Q5HTJPER-hTV4QB0ow3Yax4lJVSgkLBwAAry3OLYMMho5GmcyRFqjPIJ6RmOcNkuee8NRWoJsFOjZ7JknDlXO5NIUmj45mwqHEhPcyikUVVwV9aip6jDGs0DIFgZZ4EIepk+tCYIN0ctNuNYuwqMEAPrxM6YC5XG6oNYgilSAQAIikwqpHgEAGYAAxedhs1Kc7nXFB81ZwUUwcVjLSywxAA

**Comment by leostera** [comment]
@russelldmatt, great point! One difference between using private types and the constructor/view pattern is that the internal and the view type are not bound to be the same. This means you can evolve them separately.

For example, if you're constructing an identifier, say `Id.t` it may carry internal information for the `Id` module that should not escape:

```reason
module Id : {
  type t;
  type view = int;
  let make : () => t;
  let view: t => view;
} = {
  type t = { count: int, salt: string };
  type view = int;
  /* ... */
}
```

Refactoring `Id.t` is transparent to the users, since they only rely on `Id.view` for pattern matching.

**Comment by russelldmatt** [comment]
Cool - that makes sense. Thanks!

**Comment by leostera** [comment]
Cool, I’ll close now!

**Comment by vphantom** [comment]
I ended up here after having, too, discovered private types as a middle ground between public and abstract+view.  I'm not too sure how I'd phrase it, but I think that it should be mentioned somewhere in `patterns/constructor-view.md` that if the view type could be the same, then the `private` guarantees that only the module's functions may create instances of the type, while saving some boilerplate and some run-time copying vs the pattern.

Since lots of readers of these (excellent!) documents are probably new to the language, it's likely that, like me, they don't yet know about `private` at the time of reading.

**Comment by leostera** [comment]
@vphantom I see! In that case, I'm happy to accept pull requests documenting good usage of private types as well :)

One of my worries is that when using private types, people may still refer to them from the outside and moving from that towards a view type is a bigger change for the consumers of the library. I'd rather encourage developers to pay the cost on the library creator side.
